name: Deploy Python app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Prepare deployment package
        run: |
          # Create deployment package directory
          mkdir deployment
          # Copy only necessary files
          cp -r app.py requirements.txt web.config startup.txt deployment/
          cp -r static templates deployment/
          cp calendar_setup.py deployment/
          cd deployment
          # Create virtual environment in the deployment directory
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn
          # Create zip package
          zip -r ../package.zip ./*

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: package.zip

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check deployment logs
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          echo "Fetching application logs..."
          az webapp log tail --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} 