name: Deploy Python app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Prepare deployment package
        run: |
          mkdir deployment
          cp -r app.py requirements.txt web.config startup.txt middleware.py deployment/
          cp -r static templates deployment/
          cp calendar_setup.py config_manager.py deployment/
          cd deployment
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
          deactivate
          cd ..
          zip -r deployment.zip deployment/

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deployment.zip

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check deployment and initial logs
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          echo "Checking application startup logs (will timeout after 30 seconds)..."
          timeout 30 az webapp log tail --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || true
          echo "Deployment workflow completed." 