name: Deploy Python app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Prepare deployment package
        run: |
          # Create deployment structure
          mkdir -p deployment/app
          
          # Copy application files to app directory
          cp app.py deployment/app/
          cp application.py deployment/app/
          cp middleware.py deployment/app/
          cp calendar_setup.py deployment/app/
          cp config_manager.py deployment/app/
          cp -r static templates deployment/app/
          
          # Copy configuration files to root
          cp requirements.txt deployment/
          cp runtime.txt deployment/
          cp web.config deployment/
          
          # Create virtual environment
          cd deployment
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn
          deactivate
          cd ..
          
          # Create deployment package
          cd deployment
          zip -r ../deployment.zip .
          cd ..

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deployment.zip

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check deployment and initial logs
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          echo "Checking application startup logs (will timeout after 60 seconds)..."
          timeout 60 az webapp log tail --name ${{ vars.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || true
          echo "Deployment workflow completed." 